CC = javac
JRE = java

FILES = Coordinator.java Generator.java Buffer.java Consumer.java
EXE = hw5
all:
	$(CC) $(FILES)
run:
	$(JRE) $(EXE)
clean: 
	rm *.class

tar:
	tar -cvzf Jaime-Munoz-HW5.tar *.java *.txt Makefile	
